(defsystem :mumu-normalizer
  :name "mumu-normalizer"
  :description "mumu-normalizer is a computer algebra program
 that helps compute the Lie algebra generated by the
 differentials of an almost complex manifold."
  :author ("Jin-Cheng Guu <jcguu95@gmail.com>")
  :license "MIT"
  :version "0.0.1"
  :components ((:module "src"
                :components ((:file "package")
                             (:file "main"))))
  :serial t
  :depends-on ())
